#!/usr/bin/env python
# gtcal
# Command line interface to the Georgetown Console Calendar
#
# Author:   Benjamin Bengfort <bb830@georgetown.edu>
# Created:  Thu Mar 27 16:51:15 2014 -0400
#
# Copyright (C) 2014 Georgetown University
# For license information, see LICENSE.txt
#
# ID: gtcal [] bb830@georgetown.edu $

"""
Command line interface to the Georgetown Console Calendar
"""

##########################################################################
## Imports
##########################################################################

import sys

##########################################################################
## Main method
##########################################################################

def main(*argv):
    pass

if __name__ == '__main__':
    main(*sys.argv)
